/**
 * services/wallet_engine.js
 * Upgraded Live Market Valuation Engine
 */

class WalletEngine {
  constructor() {
    // Condition scale modifiers mapping numerical grades to real cash values
    this.conditionModifiers = {
      10: 1.00,  // Gem Mint gets 100% of maximum market value
      9:  0.85,  // Mint
      8:  0.65,  // Near Mint-Mint
      7:  0.45,  // Near Mint
      6:  0.30,  // Excellent-Mint
      5:  0.20   // Very Good / Off-Center
    };

    // Real-world baseline PSA 10 market values for sports cards
    this.marketPriceIndex = {
      "caitlin clark": 150.00,       // Base pricing index for WNBA rookie cards
      "michael jordan": 2500.00,     // 1986 Fleer Rookie baseline reference
      "lebron james": 450.00,        // Topps Rookie baseline reference
      "default_sports": 20.00        // Fallback for unrecognized sports cards
    };
  }

  /**
   * Automatically looks up a card name in the market index and computes its graded value
   * @param {string} rawCardName - The filename or text input uploaded by the user
   * @param {number} calculatedGrade - The numerical grade generated by the grading engine
   * @returns {Object} Clean breakdown of the asset value and market base price
   */
  /**
   * getModifierForGrade(numericGrade) → number
   * Returns the condition modifier fraction for a given PSA-style numeric grade.
   * Used by server.js buildStatsPayload() to compute live wallet totals.
   * @param {number} numericGrade  1–10
   * @returns {number}  Modifier fraction (0–1), or 0 if grade is out of range.
   */
  getModifierForGrade(numericGrade) {
    return this.conditionModifiers[Math.round(numericGrade)] || 0;
  }

  pricingReport({ cardName, numericGrade }) {
    // 1. Sanitize the card name to match our lookup database keys
    const nameKey = (cardName || "").toLowerCase();
    
    // 2. Identify the base market price using smart string matching
    let baseMarketPrice = this.marketPriceIndex["default_sports"];
    
    for (const key in this.marketPriceIndex) {
      if (nameKey.includes(key)) {
        baseMarketPrice = this.marketPriceIndex[key];
        break;
      }
    }

    // 3. Apply the custom grade scale condition modifier
    const modifier = this.conditionModifiers[numericGrade] || 0.15;
    const finalValuation = baseMarketPrice * modifier;

    // 4. Return an end-to-end financial asset report object
    return {
      baseMarketPrice: baseMarketPrice,
      finalValuation: parseFloat(finalValuation.toFixed(2)),
      modifierApplied: modifier
    };
  }
}

module.exports = new WalletEngine();